-- Run against the PostgreSQL database selected by DATABASE_URL.
-- Mixed-case identifiers are quoted to preserve the API's existing field names.

CREATE TABLE customers (
  "CustomerId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FullName" VARCHAR(120) NOT NULL,
  "Email" VARCHAR(180) NOT NULL,
  "Phone" VARCHAR(30) NOT NULL,
  "SecretKey" VARCHAR(255) NOT NULL,
  "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_customers_email UNIQUE ("Email")
);

CREATE TABLE "TempCust" (
  "requestId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FullName" VARCHAR(120) NOT NULL,
  "Email" VARCHAR(180) NOT NULL,
  "Phone" VARCHAR(30) NOT NULL,
  "SecretKey" VARCHAR(255) NOT NULL,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_tempcust_email UNIQUE ("Email")
);

CREATE TABLE rooms (
  "RoomId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoomNo" VARCHAR(20) NOT NULL,
  "Floor" INTEGER NOT NULL,
  "RoomCondition" VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE'
    CHECK ("RoomCondition" IN ('AVAILABLE', 'MAINTENANCE', 'BOOKED')),
  "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_rooms_roomno UNIQUE ("RoomNo")
);
CREATE INDEX idx_rooms_floor ON rooms ("Floor");

CREATE TABLE booking_requests (
  "RequestId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RequestReference" VARCHAR(80) NOT NULL,
  "CustomerId" BIGINT NOT NULL,
  "FacultyInChargeName" VARCHAR(120),
  "FacultyInChargeEmail" VARCHAR(254),
  "InDate" DATE NOT NULL,
  "OutDate" DATE NOT NULL,
  "RequestStatus" VARCHAR(20) NOT NULL DEFAULT 'HOLD'
    CHECK ("RequestStatus" IN ('HOLD', 'CONFIRMED', 'EXPIRED', 'CANCELLED')),
  "ExpiresAt" TIMESTAMPTZ NOT NULL,
  "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_booking_requests_reference UNIQUE ("RequestReference"),
  CONSTRAINT fk_booking_requests_customer
    FOREIGN KEY ("CustomerId") REFERENCES customers ("CustomerId") ON DELETE CASCADE
);
CREATE INDEX idx_booking_requests_customer ON booking_requests ("CustomerId");
CREATE INDEX idx_booking_requests_status_dates ON booking_requests ("RequestStatus", "InDate", "OutDate", "ExpiresAt");
CREATE INDEX idx_booking_requests_expires ON booking_requests ("RequestStatus", "ExpiresAt");

CREATE TABLE request_rooms (
  "RequestRoomId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RequestId" BIGINT NOT NULL,
  "RoomId" BIGINT NOT NULL,
  CONSTRAINT uq_request_rooms_pair UNIQUE ("RequestId", "RoomId"),
  CONSTRAINT fk_request_rooms_request
    FOREIGN KEY ("RequestId") REFERENCES booking_requests ("RequestId") ON DELETE CASCADE,
  CONSTRAINT fk_request_rooms_room
    FOREIGN KEY ("RoomId") REFERENCES rooms ("RoomId") ON DELETE CASCADE
);
CREATE INDEX idx_request_rooms_room ON request_rooms ("RoomId");
CREATE INDEX idx_request_rooms_room_request ON request_rooms ("RoomId", "RequestId");

CREATE TABLE bookings (
  "BookingId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingReference" VARCHAR(80) NOT NULL,
  "RequestId" BIGINT NOT NULL,
  "CustomerId" BIGINT NOT NULL,
  "FacultyInChargeName" VARCHAR(120),
  "FacultyInChargeEmail" VARCHAR(254),
  "InDate" DATE NOT NULL,
  "OutDate" DATE NOT NULL,
  "BookingStatus" VARCHAR(20) NOT NULL DEFAULT 'PENDING'
    CHECK ("BookingStatus" IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED')),
  "PaymentStatus" VARCHAR(20) NOT NULL DEFAULT 'PENDING'
    CHECK ("PaymentStatus" IN ('PENDING', 'CREATED', 'SUCCESS', 'FAILED', 'REFUNDED')),
  "ConfirmedAt" TIMESTAMPTZ,
  "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_bookings_reference UNIQUE ("BookingReference"),
  CONSTRAINT uq_bookings_request UNIQUE ("RequestId"),
  CONSTRAINT fk_bookings_request
    FOREIGN KEY ("RequestId") REFERENCES booking_requests ("RequestId") ON DELETE CASCADE,
  CONSTRAINT fk_bookings_customer
    FOREIGN KEY ("CustomerId") REFERENCES customers ("CustomerId") ON DELETE CASCADE
);
CREATE INDEX idx_bookings_customer ON bookings ("CustomerId");
CREATE INDEX idx_bookings_status ON bookings ("BookingStatus", "PaymentStatus");
CREATE INDEX idx_bookings_dates ON bookings ("InDate", "OutDate");

CREATE TABLE booking_rooms (
  "BookingRoomId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingId" BIGINT NOT NULL,
  "RoomId" BIGINT NOT NULL,
  CONSTRAINT uq_booking_rooms_pair UNIQUE ("BookingId", "RoomId"),
  CONSTRAINT fk_booking_rooms_booking
    FOREIGN KEY ("BookingId") REFERENCES bookings ("BookingId") ON DELETE CASCADE,
  CONSTRAINT fk_booking_rooms_room
    FOREIGN KEY ("RoomId") REFERENCES rooms ("RoomId") ON DELETE CASCADE
);
CREATE INDEX idx_booking_rooms_room ON booking_rooms ("RoomId");
CREATE INDEX idx_booking_rooms_room_booking ON booking_rooms ("RoomId", "BookingId");

CREATE TABLE payments (
  "PaymentId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingId" BIGINT,
  "RequestId" BIGINT,
  "RazorpayOrderId" VARCHAR(255) NOT NULL,
  "RazorpayPaymentId" VARCHAR(255),
  "RazorpaySignature" VARCHAR(255),
  "Amount" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  "Currency" VARCHAR(10) NOT NULL DEFAULT 'INR',
  "PaymentStatus" VARCHAR(20) NOT NULL DEFAULT 'CREATED'
    CHECK ("PaymentStatus" IN ('CREATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED')),
  "PaymentMethod" VARCHAR(30) NOT NULL DEFAULT 'RAZORPAY',
  "VerificationStatus" VARCHAR(20) NOT NULL DEFAULT 'PENDING'
    CHECK ("VerificationStatus" IN ('PENDING', 'VERIFIED', 'FAILED')),
  "FailureReason" VARCHAR(255),
  "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "VerifiedAt" TIMESTAMPTZ,
  CONSTRAINT uq_payments_order UNIQUE ("RazorpayOrderId"),
  CONSTRAINT fk_payments_booking
    FOREIGN KEY ("BookingId") REFERENCES bookings ("BookingId") ON DELETE SET NULL,
  CONSTRAINT fk_payments_request
    FOREIGN KEY ("RequestId") REFERENCES booking_requests ("RequestId") ON DELETE SET NULL
);
CREATE INDEX idx_payments_booking ON payments ("BookingId");
CREATE INDEX idx_payments_request ON payments ("RequestId");
CREATE INDEX idx_payments_status ON payments ("PaymentStatus", "VerificationStatus");

CREATE TABLE booking_notifications (
  "NotificationId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingId" BIGINT NOT NULL,
  "RecipientEmail" VARCHAR(255) NOT NULL,
  "RecipientName" VARCHAR(120) NOT NULL,
  "NotificationType" VARCHAR(60) NOT NULL,
  "NotificationStatus" VARCHAR(20) NOT NULL DEFAULT 'PENDING'
    CHECK ("NotificationStatus" IN ('PENDING', 'SENT', 'FAILED')),
  "SentAt" TIMESTAMPTZ,
  "ErrorMessage" TEXT,
  "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notifications_booking
    FOREIGN KEY ("BookingId") REFERENCES bookings ("BookingId") ON DELETE CASCADE
);
CREATE INDEX idx_notifications_booking ON booking_notifications ("BookingId");

INSERT INTO rooms ("RoomNo", "Floor", "RoomCondition") VALUES
('101', 1, 'AVAILABLE'),
('102', 1, 'AVAILABLE'),
('103', 1, 'AVAILABLE'),
('104', 1, 'MAINTENANCE'),
('105', 1, 'AVAILABLE'),
('201', 2, 'AVAILABLE'),
('202', 2, 'AVAILABLE'),
('203', 2, 'AVAILABLE'),
('204', 2, 'MAINTENANCE'),
('205', 2, 'AVAILABLE'),
('301', 3, 'AVAILABLE'),
('302', 3, 'AVAILABLE'),
('303', 3, 'AVAILABLE'),
('304', 3, 'AVAILABLE'),
('305', 3, 'MAINTENANCE'),
('401', 4, 'AVAILABLE'),
('402', 4, 'AVAILABLE'),
('403', 4, 'MAINTENANCE'),
('404', 4, 'AVAILABLE'),
('405', 4, 'AVAILABLE')
ON CONFLICT ("RoomNo") DO NOTHING;

SELECT 'PostgreSQL database schema created successfully.' AS status;
