-- PostgreSQL upgrade for an existing PostgreSQL database created from the
-- original guest-house schema. Back up the database before applying.

ALTER TABLE "TempCust"
  ADD COLUMN IF NOT EXISTS "FullName" VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE "TempCust"
  ALTER COLUMN "SecretKey" TYPE VARCHAR(255);
ALTER TABLE customers
  ALTER COLUMN "SecretKey" TYPE VARCHAR(255);

ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS "FacultyInChargeName" VARCHAR(120);
ALTER TABLE booking_requests
  ADD COLUMN IF NOT EXISTS "FacultyInChargeName" VARCHAR(120);
ALTER TABLE booking_requests
  ADD COLUMN IF NOT EXISTS "FacultyInChargeEmail" VARCHAR(254);
ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS "FacultyInChargeName" VARCHAR(120);
ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS "FacultyInChargeEmail" VARCHAR(254);
ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS "BookingStatus" VARCHAR(30) NOT NULL DEFAULT 'PENDING';
ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS "PaymentStatus" VARCHAR(30) NOT NULL DEFAULT 'PENDING';

CREATE UNIQUE INDEX IF NOT EXISTS uq_bookings_request
  ON bookings ("RequestId");

CREATE TABLE IF NOT EXISTS payments (
  "PaymentId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingId" BIGINT,
  "RequestId" BIGINT,
  "RazorpayOrderId" VARCHAR(255) NOT NULL,
  "RazorpayPaymentId" VARCHAR(255),
  "RazorpaySignature" VARCHAR(255),
  "Amount" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  "Currency" VARCHAR(10) NOT NULL DEFAULT 'INR',
  "PaymentStatus" VARCHAR(20) NOT NULL DEFAULT 'CREATED',
  "PaymentMethod" VARCHAR(30) NOT NULL DEFAULT 'RAZORPAY',
  "VerificationStatus" VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  "FailureReason" VARCHAR(255),
  "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "VerifiedAt" TIMESTAMPTZ,
  CONSTRAINT uq_payments_order UNIQUE ("RazorpayOrderId"),
  CONSTRAINT fk_payments_booking
    FOREIGN KEY ("BookingId") REFERENCES bookings ("BookingId") ON DELETE SET NULL,
  CONSTRAINT fk_payments_request
    FOREIGN KEY ("RequestId") REFERENCES booking_requests ("RequestId") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS booking_notifications (
  "NotificationId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BookingId" BIGINT NOT NULL,
  "RecipientEmail" VARCHAR(255) NOT NULL,
  "RecipientName" VARCHAR(120) NOT NULL,
  "NotificationType" VARCHAR(60) NOT NULL,
  "NotificationStatus" VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  "SentAt" TIMESTAMPTZ,
  "ErrorMessage" TEXT,
  "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notifications_booking
    FOREIGN KEY ("BookingId") REFERENCES bookings ("BookingId") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_booking_requests_status_dates
  ON booking_requests ("RequestStatus", "InDate", "OutDate", "ExpiresAt");
CREATE INDEX IF NOT EXISTS idx_request_rooms_room_request
  ON request_rooms ("RoomId", "RequestId");
CREATE INDEX IF NOT EXISTS idx_booking_rooms_room_booking
  ON booking_rooms ("RoomId", "BookingId");
CREATE INDEX IF NOT EXISTS idx_payments_booking ON payments ("BookingId");
CREATE INDEX IF NOT EXISTS idx_payments_request ON payments ("RequestId");
CREATE INDEX IF NOT EXISTS idx_payments_status
  ON payments ("PaymentStatus", "VerificationStatus");
CREATE INDEX IF NOT EXISTS idx_bookings_status
  ON bookings ("BookingStatus", "PaymentStatus");
CREATE INDEX IF NOT EXISTS idx_notifications_booking
  ON booking_notifications ("BookingId");
